import type {
  AiSuggestion,
  AppendixField,
  AppendixRecord,
  AppendixTable,
  ContentBlock,
  Course,
  CourseMetrics,
  CourseNode,
  EntityLink,
  Flashcard,
  FlashcardSource,
  Source,
  StudyData,
} from "@/domain/types"

const now = new Date("2026-05-03T09:00:00.000Z").toISOString()
const tomorrow = new Date("2026-05-04T09:00:00.000Z").toISOString()
const yesterday = new Date("2026-05-02T09:00:00.000Z").toISOString()

const profileId = "profile_demo"
const courseId = "course_history"
const sourceId = "source_modern_europe"

const course: Course = {
  id: courseId,
  ownerId: profileId,
  title: "European History Foundations",
  description: "A structured course for building source-linked notes, appendices, and review cards.",
  mainLanguage: "en",
  subject: "History",
  difficultyLevel: "intermediate",
  status: "active",
  examDate: "2026-06-18",
  targetDate: "2026-06-12",
  sourceType: "lecture",
  estimatedStudyMinutes: 1260,
  masteryScore: 42,
  confidenceScore: 48,
  tags: ["history", "exam-prep", "europe"],
  createdAt: now,
  updatedAt: now,
}

const nodes: CourseNode[] = [
  {
    id: "node_module_1",
    courseId,
    nodeType: "module",
    title: "State Formation",
    position: 1,
    depth: 0,
    numberingPath: [{ level: 0, ordinal: 1, label: "I", style: "roman_upper" }],
    displayNumber: "I",
    language: "en",
    isCollapsedDefault: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "node_chapter_1",
    courseId,
    parentId: "node_module_1",
    nodeType: "chapter",
    title: "The French Revolution",
    position: 1,
    depth: 1,
    numberingPath: [
      { level: 0, ordinal: 1, label: "I", style: "roman_upper" },
      { level: 1, ordinal: 1, label: "A", style: "alpha_upper" },
    ],
    displayNumber: "I.A",
    language: "en",
    isCollapsedDefault: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "node_section_1",
    courseId,
    parentId: "node_chapter_1",
    nodeType: "section",
    title: "Causes and Pressures",
    position: 1,
    depth: 2,
    numberingPath: [
      { level: 0, ordinal: 1, label: "I", style: "roman_upper" },
      { level: 1, ordinal: 1, label: "A", style: "alpha_upper" },
      { level: 2, ordinal: 1, label: "a", style: "alpha_lower" },
    ],
    displayNumber: "I.A.a",
    language: "en",
    isCollapsedDefault: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "node_subsection_1",
    courseId,
    parentId: "node_section_1",
    nodeType: "subsection",
    title: "Fiscal Crisis",
    position: 1,
    depth: 3,
    numberingPath: [
      { level: 0, ordinal: 1, label: "I", style: "roman_upper" },
      { level: 1, ordinal: 1, label: "A", style: "alpha_upper" },
      { level: 2, ordinal: 1, label: "a", style: "alpha_lower" },
      { level: 3, ordinal: 1, label: "i", style: "roman_lower" },
    ],
    displayNumber: "I.A.a.i",
    language: "en",
    isCollapsedDefault: false,
    createdAt: now,
    updatedAt: now,
  },
]

const contentBlocks: ContentBlock[] = [
  {
    id: "block_heading_fiscal",
    courseId,
    nodeId: "node_subsection_1",
    blockType: "heading",
    position: 1,
    depth: 1,
    content: { text: "Fiscal Crisis Before 1789" },
    plainText: "Fiscal Crisis Before 1789",
    language: "en",
    numberingPath: nodes[3].numberingPath,
    displayNumber: "I.A.a.i.1",
    isCollapsible: true,
    isCollapsed: false,
    version: 1,
    contentHash: "27:Fiscal Crisis Before 1789",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "block_para_estates",
    courseId,
    nodeId: "node_subsection_1",
    blockType: "paragraph",
    position: 2,
    depth: 2,
    content: {
      text: "The Estates-General was called in 1789 because the monarchy could not solve its fiscal crisis alone. Louis XVI needed consent for new taxation, but the political structure made consent difficult.",
    },
    plainText:
      "The Estates-General was called in 1789 because the monarchy could not solve its fiscal crisis alone. Louis XVI needed consent for new taxation, but the political structure made consent difficult.",
    language: "en",
    numberingPath: nodes[3].numberingPath,
    displayNumber: "",
    isCollapsible: false,
    isCollapsed: false,
    version: 1,
    contentHash: "181:The Estates-General was",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "block_def_estates",
    courseId,
    nodeId: "node_subsection_1",
    blockType: "definition",
    position: 3,
    depth: 2,
    content: {
      text: "Estates-General: an assembly representing clergy, nobility, and commoners in pre-revolutionary France.",
    },
    plainText: "Estates-General: an assembly representing clergy, nobility, and commoners in pre-revolutionary France.",
    language: "en",
    numberingPath: nodes[3].numberingPath,
    displayNumber: "",
    isCollapsible: false,
    isCollapsed: false,
    version: 1,
    contentHash: "98:Estates-General: an",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "block_note_ai",
    courseId,
    nodeId: "node_subsection_1",
    blockType: "note",
    position: 4,
    depth: 2,
    content: {
      text: "This block is a good candidate for appendix links: Louis XVI as a person, 1789 as a date, and Estates-General as a definition.",
    },
    plainText:
      "This block is a good candidate for appendix links: Louis XVI as a person, 1789 as a date, and Estates-General as a definition.",
    language: "en",
    numberingPath: nodes[3].numberingPath,
    displayNumber: "",
    isCollapsible: false,
    isCollapsed: false,
    version: 1,
    contentHash: "123:This block is a good",
    createdAt: now,
    updatedAt: now,
  },
]

const appendixTables: AppendixTable[] = [
  {
    id: "table_images",
    courseId,
    name: "Images",
    slug: "images",
    tableType: "images",
    isDefault: true,
    description: "Structured images used inline or as study references.",
    position: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "table_persons",
    courseId,
    name: "Persons",
    slug: "persons",
    tableType: "persons",
    isDefault: true,
    description: "People, authors, rulers, and historical actors.",
    position: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "table_events",
    courseId,
    name: "Events",
    slug: "events",
    tableType: "events",
    isDefault: true,
    description: "Dated events and timelines.",
    position: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "table_places",
    courseId,
    name: "Places",
    slug: "places",
    tableType: "places",
    isDefault: true,
    description: "Locations and geographic references.",
    position: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "table_definitions",
    courseId,
    name: "Definitions",
    slug: "definitions",
    tableType: "definitions",
    isDefault: true,
    description: "Terms, concepts, and formulas.",
    position: 5,
    createdAt: now,
    updatedAt: now,
  },
]

const appendixFields: AppendixField[] = appendixTables.flatMap((table) => [
  {
    id: `field_${table.slug}_summary`,
    appendixTableId: table.id,
    name: "Summary",
    slug: "summary",
    fieldType: "long_text",
    isRequired: false,
    position: 1,
    createdAt: now,
  },
  {
    id: `field_${table.slug}_source`,
    appendixTableId: table.id,
    name: "Source",
    slug: "source",
    fieldType: "text",
    isRequired: false,
    position: 2,
    createdAt: now,
  },
])

const sources: Source[] = [
  {
    id: sourceId,
    courseId,
    sourceType: "lecture",
    title: "Lecture notes: Revolution and State Formation",
    author: "Course instructor",
    citation: "Week 2 lecture packet",
    pageStart: "12",
    pageEnd: "18",
    createdAt: now,
    updatedAt: now,
  },
]

const appendixRecords: AppendixRecord[] = [
  {
    id: "record_louis",
    courseId,
    appendixTableId: "table_persons",
    title: "Louis XVI",
    recordType: "person",
    shortDescription: "King of France whose reign faced acute fiscal and political crisis before the Revolution.",
    sourceId,
    language: "en",
    aliases: ["Louis-Auguste"],
    translations: { fr: ["Louis XVI"], nl: ["Lodewijk XVI"] },
    tags: ["monarchy", "france"],
    userNotes: "Connect to taxation and consent problems.",
    version: 1,
    recordHash: "louis-xvi-v1",
    createdMethod: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "record_estates_general",
    courseId,
    appendixTableId: "table_definitions",
    title: "Estates-General",
    recordType: "definition",
    shortDescription: "Representative assembly of the three estates in pre-revolutionary France.",
    sourceId,
    language: "en",
    aliases: ["States-General"],
    translations: { fr: ["Etats generaux"], nl: ["Staten-Generaal"] },
    tags: ["institutions", "revolution"],
    userNotes: "Useful for cloze and definition cards.",
    version: 1,
    recordHash: "estates-general-v1",
    createdMethod: "manual",
    createdAt: now,
    updatedAt: now,
  },
]

const flashcards: Flashcard[] = [
  {
    id: "card_estates_basic",
    courseId,
    cardType: "definition",
    prompt: { text: "What was the Estates-General?" },
    answer: { text: "An assembly representing clergy, nobility, and commoners in pre-revolutionary France." },
    explanation: "Its 1789 meeting exposed conflicts over representation and consent.",
    hint: "Think three estates.",
    sourceExcerpt: "Estates-General: an assembly representing clergy, nobility, and commoners...",
    difficultyLevel: "intermediate",
    tags: ["definitions", "revolution"],
    language: "en",
    relatedAppendixRecordId: "record_estates_general",
    sourceWarning: false,
    masteryScore: 42,
    confidenceScore: 46,
    dueAt: yesterday,
    intervalDays: 1,
    easeFactor: 2.5,
    stability: 1,
    difficulty: 0.5,
    lapses: 1,
    reviewCount: 2,
    lastReviewedAt: "2026-05-01T10:00:00.000Z",
    staleStatus: "fresh",
    createdMethod: "manual",
    userNotes: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "card_louis_person",
    courseId,
    cardType: "person",
    prompt: { text: "Why is Louis XVI important for the fiscal crisis before 1789?" },
    answer: { text: "He needed new taxation but could not secure consent through the existing political structure." },
    explanation: "The fiscal problem pushed the monarchy toward calling the Estates-General.",
    hint: "Connect monarchy, taxation, and consent.",
    sourceExcerpt: "Louis XVI needed consent for new taxation...",
    difficultyLevel: "intermediate",
    tags: ["persons", "causation"],
    language: "en",
    relatedAppendixRecordId: "record_louis",
    sourceWarning: false,
    masteryScore: 62,
    confidenceScore: 58,
    dueAt: tomorrow,
    intervalDays: 3,
    easeFactor: 2.4,
    stability: 2,
    difficulty: 0.4,
    lapses: 0,
    reviewCount: 1,
    lastReviewedAt: "2026-05-01T11:00:00.000Z",
    staleStatus: "fresh",
    createdMethod: "manual",
    userNotes: "",
    createdAt: now,
    updatedAt: now,
  },
]

const flashcardSources: FlashcardSource[] = [
  {
    id: "card_source_estates_block",
    flashcardId: "card_estates_basic",
    sourceTargetType: "content_block",
    sourceTargetId: "block_def_estates",
    sourceVersion: 1,
    sourceHash: "98:Estates-General: an",
    sourceExcerpt: "Estates-General: an assembly representing clergy, nobility, and commoners...",
    createdAt: now,
  },
  {
    id: "card_source_louis_block",
    flashcardId: "card_louis_person",
    sourceTargetType: "content_block",
    sourceTargetId: "block_para_estates",
    sourceVersion: 1,
    sourceHash: "181:The Estates-General was",
    sourceExcerpt: "Louis XVI needed consent for new taxation...",
    createdAt: now,
  },
]

const entityLinks: EntityLink[] = [
  {
    id: "link_louis_para",
    courseId,
    fromType: "content_block",
    fromId: "block_para_estates",
    toType: "appendix_record",
    toId: "record_louis",
    linkType: "mentions",
    createdMethod: "manual",
    createdAt: now,
  },
  {
    id: "link_estates_def",
    courseId,
    fromType: "content_block",
    fromId: "block_def_estates",
    toType: "appendix_record",
    toId: "record_estates_general",
    linkType: "defines",
    createdMethod: "manual",
    createdAt: now,
  },
]

const aiSuggestions: AiSuggestion[] = [
  {
    id: "suggestion_flashcards_fiscal",
    courseId,
    suggestionType: "flashcards",
    status: "pending",
    title: "Generate 3 cards from fiscal crisis notes",
    summary: "Suggested definition, cause-effect, and person cards from the selected content block.",
    payload: {
      cards: [
        {
          cardType: "basic",
          prompt: "Why was the Estates-General called in 1789?",
          answer: "Because the monarchy could not solve the fiscal crisis alone and needed consent for new taxation.",
          sourceBlockId: "block_para_estates",
        },
      ],
    },
    model: "edge-function-placeholder",
    promptVersion: "mvp-1",
    riskLevel: "low",
    createdByContext: { blockIds: ["block_para_estates"] },
    createdAt: now,
  },
]

const metrics: CourseMetrics[] = [
  {
    courseId,
    wordCount: 64,
    characterCount: 428,
    sentenceCount: 6,
    headingCount: 1,
    contentBlockCount: contentBlocks.length,
    appendixRecordCount: appendixRecords.length,
    flashcardCount: flashcards.length,
    tokenEstimate: 92,
    dueCardCount: 1,
    weakCardCount: 1,
    coveragePercent: 50,
    updatedAt: now,
  },
]

export const defaultStudyData: StudyData = {
  profileId,
  courses: [course],
  courseNodes: nodes,
  contentBlocks,
  contentTextAnchors: [],
  appendixTables,
  appendixFields,
  appendixRecords,
  appendixRecordValues: [],
  sources,
  assets: [],
  flashcards,
  flashcardSources,
  reviewSessions: [],
  reviewAttempts: [],
  aiSuggestions,
  aiSuggestionTargets: [],
  entityLinks,
  metrics,
}
